pythonecuador/lira

design/format.md
Ref https://github.com/pythonecuador/pylearn/issues/6
=> Add document about format

lira/book.py, lira/books/basics/book.yaml, lira/books/basics/intro.rst, lira/parsers/__init__.py, lira/parsers/nodes.py, lira/parsers/rst.py, lira/validators.py, setup.py
=> Implement basic parser

docs/conf.py, lira/book.py, lira/parsers/nodes.py, setup.py, tests/data/books/example/book.yaml, tests/data/books/example/nested.rst, tests/test_book.py
Still need to add tests and figure out how to handle a dotted module path (maybe I'll leave that for another PR)
Close #28
=> Add book class

lira/book.py, lira/parsers/__init__.py, lira/parsers/nodes.py, lira/parsers/rst.py, lira/validators.py, tests/test_book.py, tests/test_rst_parser.py
- Improve documentation
Closes https://github.com/pythonecuador/lira/issues/42
=> Parser: use a string instead of a file

Makefile
=> add target docs in make file

docs/development.rst, docs/index.rst, docs/modules/index.rst
Close https://github.com/pythonecuador/lira/issues/45
=> Docs: document development

.coveragerc, .github/workflows/tests.yaml, Makefile, docs/development.rst, noxfile.py
We are still missing the codecov integration.
ref https://github.com/pythonecuador/lira/issues/31
=> Run coverage

.github/workflows/tests.yaml, codecov.yaml
Close https://github.com/pythonecuador/lira/issues/31
=> Integrate with codecov

README.md
Add the following Badges:
- documentation
- coverages
- test
- pypi
Closes #17
=> Add badges to Readme.md

lira/app.py, lira/config.py, lira/parsers/rst.py, lira/ui.py, noxfile.py
Closes https://github.com/pythonecuador/lira/issues/37
=> Setup logger

docs/development.rst, docs/index.rst
Add link to Python Ecuador and mention the project
Close https://github.com/pythonecuador/lira/issues/54
=> Mention this is a project from Python Ecuador

docs/modules/parser.rst, lira/parsers/nodes.py, noxfile.py, tests/test_nodes.py
Close https://github.com/pythonecuador/lira/issues/40
=> Add tests for nodes

docs/development.rst, lira/__main__.py
- Update docs
- We are importing this module from setup.py, so we need the __main__
check.
=> Small fixes

docs/development.rst
=> Change get for become

docs/development.rst
=> Add link to telegram group

lira/book.py, lira/parsers/nodes.py, tests/test_nodes.py, tests/test_rst_parser.py
Close https://github.com/pythonecuador/lira/issues/36
=> Nodes: use namedtuple for options

lira/book.py, lira/books/intro/book.yaml, tests/data/books/example/book.yaml, tests/test_book.py
Rename contents from book.yaml to chapters
Close https://github.com/pythonecuador/lira/issues/44
=> Rename contents from book.yaml to chapters

lira/app.py, noxfile.py, tests/test_app.py
Close https://github.com/pythonecuador/lira/issues/78
=> LiraApp: more tests

lira/book.py
I don't think this is useful.
A chapter can already have sub-sections.
=> Book: don't support subchapters

lira/parsers/nodes.py
`__str__` already fallbacks to `__repr__`
=> Override only __repr__

lira/book.py, tests/test_book.py
Closes https://github.com/pythonecuador/lira/issues/89
=> BookChapter: toc() should return a section object

tests/test_book.py
Agrega la funcion test_chapter_repr que realiza el test de la funcion repr de la clase BookChapter
Close #87
=> Agrega test de funcion repr de BookChapter

lira/ui.py, noxfile.py
Close https://github.com/pythonecuador/lira/issues/97
=> TUI: make the windows responsive

lira/ui.py
Closes https://github.com/pythonecuador/lira/issues/99
=> TUI: allow all windows to access the TUI itself

lira/ui.py
We need to pass them as a container,
so the instance doesn't change inside.
=> TUI: fix containers

lira/tui/__init__.py, lira/tui/widgets.py, lira/tui/windows.py, noxfile.py, tests/tui/test_windows.py, tests/tui/utils.py
Currently we were harcoding the type of container (HSplit).
But this depends on the type of window.
=> TUI: use dynamic container

lira/tui/__init__.py, lira/tui/windows.py, noxfile.py, tests/tui/test_windows.py
- Add tests
- Add a mini notification system
- Show notifications asynchronously
=> TUI: improve status bar

lira/tui/__init__.py, lira/tui/utils.py, lira/tui/widgets.py, lira/tui/windows.py, noxfile.py, tests/tui/test_tui.py
Also added a way to setup the title :)
Close https://github.com/pythonecuador/lira/issues/100
=> TUI: test tui

lira/tui/__init__.py, lira/tui/themes.py, lira/tui/widgets.py, lira/tui/windows.py, noxfile.py, tests/tui/test_widgets.py, tests/tui/test_windows.py, tests/tui/utils.py
Still missing tests and figure out how to add a nicer scroll margin
=> TUI: refactor list widgets

lira/tui/utils.py, lira/tui/windows.py, noxfile.py, setup.py, tests/data/books/renderer/book.yaml, tests/data/books/renderer/code-blocks.rst, tests/tui/test_renderer.py
Let's bring color to Lira!
Tests are missing
Close #125
=> TUI: syntax highlight for code-blocks

lira/tui/widgets.py, tests/tui/test_widgets.py
Close https://github.com/pythonecuador/lira/issues/132
=> TUI: allow textarea to handle mouse events from the formatted_text

lira/books/intro/showcase.rst, lira/parsers/__init__.py, lira/parsers/nodes.py, lira/parsers/rst.py, lira/tui/render.py, lira/tui/windows.py, tests/data/books/example/intro.rst, tests/data/books/renderer/book.yaml, tests/data/books/renderer/test-blocks.rst, tests/test_nodes.py, tests/test_rst_parser.py, tests/tui/test_renderer.py
Close https://github.com/pythonecuador/lira/issues/130
=> TUI: add renderer and render test-block

lira/tui/__init__.py, lira/tui/render.py, lira/tui/widgets.py, lira/tui/windows.py, noxfile.py, tests/tui/test_windows.py
Closes https://github.com/pythonecuador/lira/issues/141
=> TUI: restore cursor after text is changed

lira/tui/__init__.py, lira/tui/render.py, lira/tui/utils.py, lira/tui/widgets.py, lira/tui/windows.py, noxfile.py, setup.py, tests/tui/test_widgets.py
Close https://github.com/pythonecuador/lira/issues/139
=> TUI: implement copy to clipboard

lira/parsers/nodes.py, lira/parsers/rst.py, lira/tui/render.py, lira/tui/widgets.py, noxfile.py, tests/test_book.py, tests/test_nodes.py, tests/test_rst_parser.py
Close https://github.com/pythonecuador/lira/issues/147
=> Refactor nodes

.github/workflows/tests.yaml, docs/modules/index.rst, docs/modules/parser.rst, docs/modules/validators.rst, lira/app.py, lira/books/intro/__init__.py, lira/books/intro/showcase.rst, lira/parsers/nodes.py, lira/parsers/rst.py, lira/tui/render.py, lira/validators.py, noxfile.py, tests/data/books/example/intro.rst, tests/data/books/renderer/test-blocks.rst, tests/test_nodes.py, tests/test_rst_parser.py, tests/tui/test_renderer.py
=> Implement check action
